version: '3.8'

services:
  web1:
    image: ${DOCKER_REGISTRY-}web1
    build:
      context: .
      dockerfile: Web1/Dockerfile
    ports:
        - "2000:2000"
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
        - "3000:3000"

